<?php 
    $form = $this->eventsForm;
    $form->setAttribute('name', 'eventsForm');
    $form->setAttribute('id', 'eventsForm');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
?>

<div id="addEventModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                <h4>Add Event</h4>
            </div>
            <div id="modalBody" class="modal-body"> 
                <form method="POST" action="/application/addEvent" id="existingContactSearchForm">
                    <h3>Event Details</h3>
                    <div class="form-horizontal">
                        <div class="form-group">
                            <div class="col-md-12 col-lg-12">
                                <?php echo $this->formLabel($form->get('start'));?>
                                <?php echo $this->formDate($form->get('start'));?>
                                <?php echo $this->FormElementErrors($form->get('start'));?>
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <?php echo $this->formLabel($form->get('end'));?>
                                <?php echo $this->formDate($form->get('end'));?>
                                <?php echo $this->FormElementErrors($form->get('end'));?>
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <?php echo $this->formLabel($form->get('title'));?>
                                <?php echo $this->formText($form->get('title'));?>
                                <?php echo $this->FormElementErrors($form->get('title'));?>
                            </div>
                            <div class="col-md-12 col-lg-12">
                                <?php echo $this->formLabel($form->get('description'));?>
                                <?php echo $this->formText($form->get('description'));?>
                                <?php echo $this->FormElementErrors($form->get('description'));?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type='button' data-toggle='tooltip' title='Add Event' class='btn btn-success' 
                    onclick='addEvent();'>
                    <span class='glyphicon glyphicon-ok' aria-hidden='true'></span> Add Event
                </button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    <span class='glyphicon glyphicon-cancel' aria-hidden='true'></span>Cancel
                </button>
            </div>
        </div>
    </div>
</div>
