<?php 
?>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3>Event Details</h3>
        </div>
        <div class="modal-body"> 
            <h4>Event Details</h4>
            <div id="event-id" data=""></div>
            <div class="row">
                <div class="col-md-12">    
                    <strong>Title: </strong>
                    <div id="event-title"></div>
                </div>            
                <div class="col-md-12">    
                    <strong>Description: </strong>
                    <div id="event-description"></div>
                </div>            
                <div class="col-md-12">    
                    <strong>Location: </strong>
                    <div id="event-location"></div>
                </div>            
                <div class="col-md-12">    
                    <strong>Start: </strong>
                    <div id="event-start"></div>
                </div>            
                <div class="col-md-12">    
                    <strong>End: </strong>
                    <div id="event-end"></div>
                </div>            
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" title="Edit Event" onclick="editEvent();">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit Event
            </button>
            <button type="button" class="btn btn-danger" title="Delete Event" onclick="deleteEvent();">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Event
            </button>
        </div>
    </div>
</div>
