<?php 
?>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3>Event Details</h3>
        </div>
        <div class="modal-body"> 
            <h4>Event Details</h4>
            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" title="Edit Event" onclick="editEvent();">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Edit Event
            </button>
            <button type="button" class="btn btn-success" title="Delete Event" onclick="deleteEvent();">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Delete Event
            </button>
        </div>
    </div>
</div>
