<div id="suggest-songs">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">Set List Songs</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-12">
                    <h5>Songs</h5>
                    <table class="table table-striped table-condensed table-fixed">
                        <thead>
                            <tr>
                                <th width="60%">Song Name</th>
                                <th width="40%">Artist</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(is_array($this->setListSongs)): ?>
                                <?php foreach($this->setListSongs as $setListSong): ?>
                                <tr>
                                    <td width="60%">
                                    	<?php echo $this->escapeHtml($setListSong['Song_Name']); ?>
                                	</td>
                                    <td width="40%">
                                    	<?php echo $this->escapeHtml($setListSong['Song_Artist']); ?>
                                	</td>
                                </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
