<?php
    $form = $this->addSongForm;
    $form->setAttribute('action', $this->url('application', ['action' => 'addSong']));
    $form->setAttribute('name', 'add-song-form');
    $form->setAttribute('id', 'add-song-form');
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<div id="suggest-songs">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">Suggested Songs</h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-horizontal">
                        <?php echo $this->formHidden($form->get('songStatus'));?>
                        <?php echo $this->formHidden($form->get('recordActive'));?>
                        <div class="form-group">
                            <div class="col-md-5">
                                <?php echo $this->formLabel($form->get('songName'));?>
                                <?php echo $this->formText($form->get('songName'));?>
                                <?php echo $this->FormElementErrors($form->get('songName'));?>
                            </div>
                            <div class="col-md-5">
                                <?php echo $this->formLabel($form->get('songArtist'));?>
                                <?php echo $this->formText($form->get('songArtist'));?>
                                <?php echo $this->FormElementErrors($form->get('songArtist'));?>
                            </div>
                            <div class="col-md-2">
                                <div class="row">
                                    <button type="button" class="btn btn-success" title="submit" onclick="submitAddSongForm();" id="addSongSubmitButton">
                                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span> Add Song
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-condensed table-fixed">
                        <thead>
                            <tr>
                                <th width="40%">Song Name</th>
                                <th width="40%">Artist</th>
                                <th width="20%">Controls</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(is_array($this->suggestedSongs)): ?>
                                <?php foreach($this->suggestedSongs as $suggestedSong): ?>
                                <tr>
                                    <td width="40%">
                                    	<?php echo $this->escapeHtml($suggestedSong['Song_Name']); ?>
                                	</td>
                                    <td width="40%">
                                    	<?php echo $this->escapeHtml($suggestedSong['Song_Artist']); ?>
                                	</td>
                                    <td width="20%">
                                    	
                                	</td>
                                </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag();
