<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php 
            echo $this->headTitle('The Minute Steaks')->setSeparator(' - ')->setAutoEscape(false);
            echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
            echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

            // Styles
            $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']);
            $this->headLink()->prependStylesheet($this->basePath('css/custom.css'));
            $this->headLink()->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css');
            $this->headLink()->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css');
            echo $this->headLink();

            $this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js');
            $this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js');
            echo $this->headScript();
        ?>
    </head>
    <body>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
