<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('The Minute Steaks')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/custom.css'))
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css')
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css')
            ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js')
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/flame.png') ?>" height="28" alt="Rock and Roll <?= \Application\Module::VERSION ?>"/>&nbsp;The Minute Steaks
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right navbar-user">
                        <li class='dropdown'>
                            <a href=# class='dropdown-toggle' data-toggle="dropdown"><i class="fa fa-table"></i> Menu <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/">Home</a></li>
                                <li><a href="/calendar">Calendar</a></li>
                                <li><a href="/songs">Songs</a></li>
                                <li><a href="/users">Admin</a></li>
                                <hr>
                                <li><a href="/logout"><b>Logout</b></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by James Botwright.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
