<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('The Minute Steaks')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/custom.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('fullcalendar-3.4.0/fullcalendar.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('fullcalendar-3.4.0/lib/jquery.min.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('fullcalendar-3.4.0/lib/moment.min.js'))
            ->appendFile($this->basePath('fullcalendar-3.4.0/fullcalendar.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/flame.png') ?>" height="28" alt="Rock and Roll <?= \Application\Module::VERSION ?>"/>&nbsp;The Minute Steaks
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="active">
                            <a class="navbar-brand" href="<?= $this->url('logout') ?>">
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li class="dropdown user-dropdown">
<!--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user"></i> 
                            <?php echo $this->user_Session->username . " - " . $user_Session->role; ?> <b class="caret"></b>
                        </a>-->
                        <ul class="dropdown-menu">
<!--                            <li><a href="/users/profile"><i class="fa fa-user"></i> Profile</a></li>
                            <li class="divider"></li>-->
                            <li><a href="<?php echo $this->url('logout');?>"><i class="fa fa-power-off"></i> Log Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by James Botwright.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
