<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<div class="row">
    <div class="col-md-6">
        <div id="calendar"></div>
    </div>
</div>

<div class="modal fade" id="editDocumentRegisterModal" tabindex="-1" role="dialog" aria-labelledby="editDocumentRegisterModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <?php echo $this->partial('application/index/partial/add-event-modal.phtml', ['eventsForm' => $this->eventsForm]); ?>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/calendar.js?'.uniqid();?>"></script>
