<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<div class="row">
    <div class="col-md-10">
        <div id="calendar"></div>
    </div>
</div>

<div class="modal fade" id="add-event-modal">
    <?php echo $this->partial('application/index/partial/add-event-modal.phtml', ['addEventsForm' => $this->addEventsForm]); ?>
</div>

<div class="modal fade" id="edit-event-modal">
    <?php echo $this->partial('application/index/partial/add-event-modal.phtml', ['editEventsForm' => $this->editEventsForm]); ?>
</div>

<div class="modal fade" id="event-details-modal">
    <?php echo $this->partial('application/index/partial/event-details-modal.phtml'); ?>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/calendar.js?'.uniqid();?>"></script>
