<div class="jumbotron">
    <h1>The Minute Steaks Portal</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <button type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Calendar"  onclick="window.open('/calendar', '_self')">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Calendar
        </button>
    </div>
</div>
