
<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<div class="jumbotron">
    <h1>The Minute Steaks Portal</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <button type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Calendar"  onclick="window.open('/calendar', '_self')">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Events Calendar
        </button>
    </div>
    <div class="col-md-4">
        <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Calendar"  onclick="window.open('/songs', '_self')">
            <span class="glyphicon glyphicon-music" aria-hidden="true"></span> Current Song Lists
        </button>
    </div>
</div>
<br /><br />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">Upcoming Events</h4>
            </div>
            <div class="panel-body">
                <?php if(is_array($this->upcomingEvents)): ?>
                <?php foreach($this->upcomingEvents as $upcomingEvent): ?>
                    <div class="well">
                        <div class="row">
                            <div class="col-md-12">    
                                <strong>Title: </strong><?php echo $this->escapeHtml($upcomingEvent['title']);?>
                            </div>            
                            <div class="col-md-12">    
                                <strong>Description: </strong><?php echo $this->escapeHtml($upcomingEvent['description']);?>
                            </div>            
                            <div class="col-md-12">    
                                <strong>Location: </strong><?php echo $this->escapeHtml($upcomingEvent['location']);?>
                            </div>            
                            <div class="col-md-12">    
                                <strong>Start: </strong><?php echo $this->escapeHtml($upcomingEvent['start']);?>
                            </div>            
                            <div class="col-md-12">    
                                <strong>End: </strong><?php echo $this->escapeHtml($upcomingEvent['end']);?>
                            </div>            
                        </div>
                    </div>
                <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/index.js?'.uniqid();?>"></script>
