
<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<div class="jumbotron">
    <h1>The Minute Steaks Portal</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <button type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Calendar"  onclick="window.open('/calendar', '_self')">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Calendar
        </button>
    </div>
    <div class="col-md-4">
        <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Calendar"  onclick="window.open('/songs', '_self')">
            <span class="glyphicon glyphicon-music" aria-hidden="true"></span> Song Lists
        </button>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Next Practice</h4>
    </div>
    <div class="panel-body">
        <h3>Sunday 2nd July @ 12</h3>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/index.js?'.uniqid();?>"></script>
