<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<h2>Area will contain editable lists to list current songs, songs to learn & 'reserves' :)</h2>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-6">
        	<?php echo $this->partial('application/index/partial/suggested-songs-table.phtml', [
                'suggestedSongs' => $this->suggestedSongs, 
                'addSongForm'    => $this->addSongForm,
            ]); ?>
    	</div>
        <div class="col-md-6">
        	<?php echo $this->partial('application/index/partial/set-list-songs-table.phtml', [
                'setListSongs' => $this->setListSongs, 
            ]); ?>
    	</div>
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
        	<?php echo $this->partial('application/index/partial/reserved-songs-table.phtml', [
                'reservedSongs' => $this->reservedSongs, 
            ]); ?>
    	</div>
        <div class="col-md-6">
        	<?php echo $this->partial('application/index/partial/removed-songs-table.phtml', [
                'removedSongs' => $this->removedSongs, 
            ]); ?>
    	</div>
    </div>
</div>

<div class="row">
    <div class="col-md-10">
        <div id="current-songs"></div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/songs.js?'.uniqid();?>"></script>
