<div class="se-pre-con"></div>
<div class="overlay">
	<div id="loading-img"></div>
</div>

<h2>Area will contain editable lists to list current songs, songs to learn & 'reserves' :)</h2>

<div class="row">
    <div class="col-md-10">
        <div id="current-songs"></div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath() . '/js/songs.js?'.uniqid();?>"></script>
